import { coerceBooleanProperty } from '@angular/cdk/coercion';
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  input,
  model,
  output,
} from '@angular/core';

import {
  DaffDisableable,
  DaffDisableableDirective,
  DaffSizableDirective,
  DaffSizeSmallType,
} from '@daffodil/design';

import {
  DaffSwitchLabelPosition,
  DaffSwitchLabelPositionEnum,
} from './label-position';

let switchIncrementalId = 0;

export type DaffSwitchSize = DaffSizeSmallType;

/**
 * The switch component provides a way to toggle between two settings.
 *
 * ```html
 * <daff-switch>Label</daff-switch>
 * ```
 */
@Component({
  selector: 'daff-switch',
  templateUrl: './switch.component.html',
  styleUrl: './switch.component.scss',
  hostDirectives: [
    {
      directive: DaffSizableDirective,
      inputs: ['size'],
    },
    {
      directive: DaffDisableableDirective,
      inputs: ['disabled'],
    },
  ],
  host: {
    class: 'daff-switch',
    '[class.checked]': 'checked()',
    '[class.left]': 'labelPosition() === "left"',
    '[class.right]': 'labelPosition() === "right"',
    '[class.top]': 'labelPosition() === "top"',
    '[class.bottom]': 'labelPosition() === "bottom"',
  },
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DaffSwitchComponent extends DaffSizableDirective<DaffSwitchSize> implements DaffDisableable {
  /**
   * The position of the label relative to the switch.
   */
  labelPosition = input<DaffSwitchLabelPosition>(DaffSwitchLabelPositionEnum.LEFT);

  constructor(private disabledDirective: DaffDisableableDirective) {
    super();
  }

  /**
   * Whether the switch is disabled.
   */
  @Input() get disabled() {
    return this.disabledDirective.disabled();
  }
  set disabled(value: any) {
    this.disabledDirective.disabled.set(coerceBooleanProperty(value));
  }

  /**
   * Current state of switch (on/off).
   */
  checked = model(false);

  /**
   * @docs-private
   */
  labelId: string = 'daff-switch-' + switchIncrementalId++ + '-label';

  /**
   * The unique id of the switch. Defaults to an autogenerated value. When using this,
   * it's your responsibility to ensure that the id for each switch is unique.
   *
   * It gets assigned to the `for` attribute on the `<label>` inside of the switch.
   */
  id = input('daff-switch-' + switchIncrementalId++);

  /**
   * Output event triggered when the switch has been toggled.
   */
  toggled = output<boolean>();

  /**
   * @docs-private
   */
  onToggle() {
    if (!this.disabled) {
      this.checked.set(!this.checked());
      this.toggled.emit(this.checked());
    }
  }
}
