/**
 * An enum for the cart error codes.
 * Each error code is unique to an error class.
 */
export enum DaffCartErrorCodes {
  CART_RESOLUTION = 'DAFF_CART_RESOLUTION',
  CART_STORAGE_RESOLUTION = 'DAFF_CART_STORAGE_RESOLUTION',
  CART_SERVER_SIDE_RESOLUTION = 'DAFF_CART_SERVER_SIDE_RESOLUTION',
  CART_NOT_FOUND_OR_CREATED_RESOLUTION = 'DAFF_CART_NOT_FOUND_OR_CREATED_RESOLUTION',
  EXCEEDED_MAX_RESOLUTION_ATTEMPTS = 'DAFF_CART_EXCEEDED_MAX_RESOLUTION_ATTEMPTS',
}
