/**
 * The error codes applicable to the filter behaviors of `@daffodil/category`.
 *
 * @docs-private
 */
export enum DaffCategoryFilterErrorCodes {
  FILTER_REQUEST_TYPE_MISMATCH = 'DAFF_CATEGORY_FILTER_REQUEST_TYPE_MISMATCH',
  FILTER_REQUEST_NAME_MISMATCH = 'DAFF_CATEGORY_FILTER_REQUEST_NAME_MISMATCH',
  FILTER_NOT_FOUND = 'DAFF_CATEGORY_FILTER_NOT_FOUND',
  UNKNOWN_FILTER_TYPE = 'DAFF_CATEGORY_UNKNOWN_FILTER_TYPE',
}
