export enum DaffCategoryFilterErrorCodes {
  CATEGORY_FILTER_REQUEST_TYPE_MISMATCH = 'DAFF_CATEGORY_FILTER_REQUEST_TYPE_MISMATCH',
  CATEGORY_FILTER_NOT_FOUND = 'DAFF_CATEGORY_FILTER_NOT_FOUND',
  CATEGORY_UNKNOWN_FILTER_TYPE = 'DAFF_CATEGORY_UNKNOWN_FILTER_TYPE',
}
