/* eslint-disable @angular-eslint/no-input-rename */
import {
  ChangeDetectionStrategy,
  Component,
  ContentChild,
  effect,
  inject,
  input,
  output,
  signal,
} from '@angular/core';
import {
  ControlValueAccessor,
  NgControl,
} from '@angular/forms';

import {
  DaffErrorMessageComponent,
  DaffHintComponent,
} from '@daffodil/design/form';

import {
  DaffRadioSetOrientation,
  DaffRadioSetOrientationEnum,
} from '../helpers/radio-set-orientation';

const radioSetUniqueId = 0;

@Component({
  selector: 'daff-radio-set',
  templateUrl: './radio-set.component.html',
  styleUrl: './radio-set.component.scss',
  host: {
    class: 'daff-radio-set',
    role: 'radiogroup',
    '[class.vertical]': 'orientation() === "vertical"',
    '[class.horizontal]': 'orientation() === "horizontal"',
  },
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DaffRadioSetComponent implements ControlValueAccessor {
  /**
   * @docs-private
   */
  @ContentChild(DaffHintComponent) private _hint: DaffHintComponent;
  /**
   * @docs-private
   */
  @ContentChild(DaffErrorMessageComponent) private _error: DaffErrorMessageComponent;

  private ngControl = inject(NgControl, { self: true, optional: true });

  /**
   * The unique id of a radio set. Defaults to an autogenerated value. When using this,
   * it's your responsibility to ensure that the id for each radio set is unique.
   *
   * It gets assigned to the `aria-labelledby` attribute for the radiogroup wrapper.
   */
  id = input<string>(`daff-radio-set-${radioSetUniqueId}`);

  /**
   * The form element name.
   */
  name = input<string>();

  /**
   * Value currently selected for a radio set. This is ignored when a form control is used.
   */
  _inputValue = input(undefined, {
    alias: 'value',
  });

  /**
   * Whether or not a radio set is disabled. This is ignored if a form control is used.
   */
  _inputDisabled = input<boolean>(false, {
    alias: 'disabled',
  });

  /**
   * The orientation of a radio set. Defaults to `vertical`.
   */
  orientation = input<DaffRadioSetOrientation, DaffRadioSetOrientation | null | undefined>(DaffRadioSetOrientationEnum.Vertical, {
    transform: (value: DaffRadioSetOrientation | null | undefined): DaffRadioSetOrientation => value || DaffRadioSetOrientationEnum.Vertical,
  });

  /** The tabindex passed down to each radio. Defaults to `0`. */
  tabIndex = input<number>(0);

  /**
   * Event fired when the value has changed.
   */
  valueChange = output<any>();

  /** Value currently selected for a radio set. */
  value = signal(undefined);

  /**
   * @docs-private
   */
  disabled = signal(false);

  /**
   * @docs-private
   */
  hintId = this.id + '-hint';

  /**
   * @docs-private
   */
  errorMessageId = this.id + '-error';

  /**
   * @docs-private
   *
   * Part of ControlValueAccessor.
   */
  _onChange: () => unknown;

  /**
   * @docs-private
   *
   * Part of ControlValueAccessor.
   */
  _onTouch: () => unknown;

  constructor() {
    if (this.ngControl) {
      this.ngControl.valueAccessor = this;
    }

    if (!this.ngControl) {
      effect(() => {
        this.value.set(this._inputValue());
      });

      effect(() => {
        this.disabled.set(this._inputDisabled());
      });
    }

    effect(() => {
      this.valueChange.emit(this.value());
    });
  }

  /**
   * @docs-private
   */
  hasHint() {
    return this._hint ? true : false;
  }

  /**
   * @docs-private
   */
  hasErrorMessage() {
    return this._error ? true : false;
  }

  /**
   * @docs-private
   *
   * Part of ControlValueAccessor.
   */
  writeValue(obj: any): void {
    this.value.set(obj);
  }

  /**
   * @docs-private
   *
   * Part of ControlValueAccessor.
   */
  registerOnChange(fn: any): void {
    this._onChange = fn;
  }

  /**
   * @docs-private
   *
   * Part of ControlValueAccessor.
   */
  registerOnTouched(fn: any): void {
    this._onTouch = fn;
  }

  /**
   * @docs-private
   *
   * Part of ControlValueAccessor.
   */
  setDisabledState?(isDisabled: boolean): void {
    this.disabled.set(isDisabled);
  }
}
