import {
  Component,
  DebugElement,
  signal,
  WritableSignal,
} from '@angular/core';
import {
  ComponentFixture,
  TestBed,
} from '@angular/core/testing';
import { By } from '@angular/platform-browser';

import { DaffRovingTabIndexService } from '@daffodil/design';

import { DaffRovingTabIndexBoundaryDirective } from './roving-tab-index-boundary.directive';

@Component({
  template: `
		<div data-set [rtiBoundary]="rtiBoundaryValue"></div>
		<div data-autogenerated rtiBoundary></div>
		<div data-autogenerated rtiBoundary></div>
		<div data-autogenerated rtiBoundary></div>
	`,
  imports: [
    DaffRovingTabIndexBoundaryDirective,
  ],
})
class WrapperComponent {
  rtiBoundaryValue: string;
}

describe('@daffodil/design | DaffRovingTabIndexBoundaryDirective', () => {
  let fixture: ComponentFixture<WrapperComponent>;
  let wrapper: WrapperComponent;
  let de: DebugElement;
  let directive: DaffRovingTabIndexBoundaryDirective;
  let serviceSpy: jasmine.SpyObj<DaffRovingTabIndexService>;
  let groupSpy: WritableSignal<string>;

  beforeEach(() => {
    groupSpy = signal('');
    serviceSpy = jasmine.createSpyObj('DaffRovingTabIndexService', ['enter'], { group: groupSpy });

    TestBed.configureTestingModule({
      imports: [
        WrapperComponent,
      ],
      providers: [
        {
          provide: DaffRovingTabIndexService,
          useValue: serviceSpy,
        },
      ],
    });

    fixture = TestBed.createComponent(WrapperComponent);
    wrapper = fixture.componentInstance;
    fixture.detectChanges();
    de = fixture.debugElement.query(By.css('[data-set]'));
    directive = de.injector.get(DaffRovingTabIndexBoundaryDirective);
  });

  it('should create', () => {
    expect(directive).toBeTruthy();
  });

  it('should accept rti as an input', () => {
    wrapper.rtiBoundaryValue = 'rtiTest';
    fixture.detectChanges();
    expect(directive.rtiBoundary()).toEqual(wrapper.rtiBoundaryValue);
  });

  describe('when the space key is pressed', () => {
    beforeEach(() => {
      (<HTMLElement>de.nativeElement).dispatchEvent(new KeyboardEvent('keydown', { key: 'Space' }));
      fixture.detectChanges();
    });

    it('should leave the group', () => {
      expect(serviceSpy.enter).toHaveBeenCalledWith(directive.effectiveBoundary());
    });
  });

  describe('autogenerated boundary IDs', () => {
    let directives: Array<DaffRovingTabIndexBoundaryDirective>;

    beforeEach(() => {
      directives = fixture.debugElement.queryAll(By.css('[data-autogenerated]')).map((d) => d.injector.get(DaffRovingTabIndexBoundaryDirective));
    });

    it('should autogenerate boundary IDs when non are present', () => {
      directives.forEach((d) => {
        expect(d.effectiveBoundary()).toBeTruthy();
      });
    });

    it('should avoid collisions between autogenerated IDs', () => {
      directives.forEach((d) => {
        expect(directives.filter((dd) => dd.effectiveBoundary() === d.effectiveBoundary()).length).toEqual(1);
      });
    });
  });
});
