import {
  computed,
  Directive,
  forwardRef,
  inject,
  input,
} from '@angular/core';

import {
  DAFF_ROVING_TAB_INDEX_BOUNDARY,
  DaffRovingTabIndexBoundary,
} from './roving-tab-index-boundary.token';
import { DaffRovingTabIndexService } from './roving-tab-index-group.service';
import { DaffRovingTabIndexDirective } from './roving-tab-index.directive';

/**
 * Defines the boundary of an RTI group.
 */
@Directive({
  // eslint-disable-next-line @angular-eslint/directive-selector
  selector: '[rtiBoundary]',
  host: {
    '[attr.data-rti-boundary]': 'effectiveBoundary()',
    '(keydown.space)': 'enterGroup($event)',
  },
  hostDirectives: [
    DaffRovingTabIndexDirective,
  ],
  providers: [
    {
      provide: DAFF_ROVING_TAB_INDEX_BOUNDARY,
      useExisting: forwardRef(() => DaffRovingTabIndexBoundaryDirective),
    },
  ],
})
export class DaffRovingTabIndexBoundaryDirective implements DaffRovingTabIndexBoundary {
  /**
   * Don't touch this directly. Use `_uniqueId`.
   */
  private static _uniqueIdCounter = 0;

  /**
   * Don't touch this directly. Use `_uniqueId`.
   */
  private _cachedUniqueId: string | undefined;
  private get _uniqueId(): string {
    if (!this._cachedUniqueId) {
      this._cachedUniqueId = `ε-rtiBoundary-${DaffRovingTabIndexBoundaryDirective._uniqueIdCounter++}`;
    }
    return this._cachedUniqueId;
  }

  private readonly groupService = inject(DaffRovingTabIndexService);

  /**
   * The name of the group for which that this element will act as boundary.
   * Optional, will be autogenerated to a unique name if omitted.
   */
  readonly rtiBoundary = input<string | null>(null);
  /**
   * The name of the group defined by this boundary.
   */
  readonly effectiveBoundary = computed(() => this.rtiBoundary() || this._uniqueId);

  /**
   * @docs-private
   */
  enterGroup(evt: Event) {
    evt.preventDefault();
    evt.stopPropagation();
    this.groupService.enter(this.effectiveBoundary());
  }
}
