export enum DaffAuthDriverErrorCodes {
  AUTHENTICATION_FAILED = 'DAFF_AUTH_AUTHENTICATION_FAILED',
  INVALID_API_RESPONSE = 'DAFF_AUTH_INVALID_API_RESPONSE',
  REGISTRATION_FAILED = 'DAFF_AUTH_REGISTRATION_FAILED',
  UNAUTHORIZED = 'DAFF_AUTH_UNAUTHORIZED',
}
