export enum MagentoCheckoutPlaceOrderGraphQlErrorCode {
  CART_NOT_FOUND = 'CART_NOT_FOUND',
  CART_NOT_ACTIVE = 'CART_NOT_ACTIVE',
  GUEST_EMAIL_MISSING = 'GUEST_EMAIL_MISSING',
  UNABLE_TO_PLACE_ORDER = 'UNABLE_TO_PLACE_ORDER',
  UNDEFINED = 'UNDEFINED',
}
