# specific branch build with batching
trigger:
  branches:
    include:
    - master
    - develop
pr:
  autoCancel: true
  branches:
    include:
    - master
    - develop
variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
jobs:
  - job: Lint
    displayName: Lint
    pool:
      vmImage: "Ubuntu 16.04"
    strategy:
      matrix:
        node_8_x:
          node_version: 8.x
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: Set Node Version

      - task: CacheBeta@0
        inputs:
          key: $(Build.SourcesDirectory)/package-lock.json
          path: $(npm_config_cache)
        displayName: Cache npm

      - script: npx npm ci
        displayName: Install Dependencies

      - script: npx lerna run lint
        displayName: Lint

  - job: Build_And_Test
    displayName: Build And Test
    pool:
      vmImage: "Ubuntu 16.04"
    strategy:
      matrix:
        node_8_x:
          node_version: 8.x
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: Set Node Version

      - task: CacheBeta@0
        inputs:
          key: $(Build.SourcesDirectory)/package-lock.json
          path: $(npm_config_cache)
        displayName: Cache npm

      - script: npm ci
        displayName: Install Dependencies

      - script: npx lerna run build && npx lerna run test
        displayName: Build & Test

      - task: CopyFiles@2
        displayName: Prepare Artifact Staging Directory
        inputs:
          sourceFolder: dist
          contents: '**/*' 
          targetFolder: $(Build.ArtifactStagingDirectory)

      - task: PublishBuildArtifacts@1
        displayName: "Publish Daff.io Serverless Artifact"
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)/apps/daffio' 
          artifactName: 'daffio-serverless' 
          parallel: true
          parallelCount: 8
  
  # - job: Deploy_Daffio_To_Now
  #   displayName: Deploy Daffio To Now
  #   pool: 
  #     vmImage: "Ubuntu 16.04"
  #   strategy:
  #     matrix:
  #       node_8_x:
  #         node_version: 8.x
  #   steps:
  #     - task: NodeTool@0
  #       inputs:
  #         versionSpec: $(node_version)
  #       displayName: Set Node Version
      
  #     - script: npm install -g lerna @angular/cli now
  #       displayName: Install Build Tools
        
  #     - script: cd dist/apps/daffio && now --scope="graycoreio" --token=$(NOW_DEPLOYMENT_TOKEN)
  #       displayName: Deploy to Now

