import {
  Overlay,
  OverlayModule,
  OverlayRef,
} from '@angular/cdk/overlay';
import {
  PortalModule,
  TemplatePortal,
} from '@angular/cdk/portal';
import {
  DOCUMENT,
  NgTemplateOutlet,
} from '@angular/common';
import {
  Component,
  ChangeDetectionStrategy,
  ViewEncapsulation,
  Input,
  ChangeDetectorRef,
  OnInit,
  ElementRef,
  Inject,
  Optional,
  Self,
  ContentChild,
  ViewChild,
  OnDestroy,
  booleanAttribute,
} from '@angular/core';
import {
  ControlValueAccessor,
  NgControl,
  Validators,
} from '@angular/forms';
import {
  Subject,
  delay,
  map,
  merge,
  of,
  takeUntil,
  tap,
} from 'rxjs';

import {
  DaffFormFieldComponent,
  DaffFormFieldControl,
  DaffOpenableDirective,
} from '@daffodil/design';

import { DaffSelectOptionDirective } from '../option/option.directive';

let daffSelectOtionsId = 0;

/**
 * DaffSelectComponent is a form control component that presents a list of selectable options,
 * similar to the native `<select>` element we call `<daff-native-select>`.
 *
 */
@Component({
  selector: 'daff-select',
  templateUrl: './select.component.html',
  styleUrls: ['./select.component.scss'],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  hostDirectives: [
    {
      directive: DaffOpenableDirective,
    },
  ],
  host: {
    class: 'daff-select',
    '[attr.aria-labelledby]': 'ariaLabelledBy',
  },
  providers: [

    { provide: DaffFormFieldControl, useExisting: DaffSelectComponent },
  ],
  imports: [
    NgTemplateOutlet,
    OverlayModule,
    PortalModule,
  ],
})
export class DaffSelectComponent<T = unknown> extends DaffFormFieldControl<string> implements DaffFormFieldControl<string>, OnInit, OnDestroy, ControlValueAccessor {
  /** @docs-private */
  controlType = 'custom-select';

  /**
   * @docs-private
   */
  supportsAutoLabelling = false;

  private _destroyed = new Subject<boolean>();
  private _overlay: OverlayRef;
  private _value = null;
  private _highlighted = 0;

  /**
   * @docs-private
   */
  get focused() {
    return this.document.activeElement === this.buttonElement?.nativeElement || this.document.activeElement === this.optionsElement?.nativeElement;
  }

  /**
   * @docs-private
   */
  get raised() {
    return this.focused && this.isOpen;
  }

  /** @docs-private */
  focus() {
    (<HTMLElement>this.buttonElement?.nativeElement)?.focus();
    this.emitState();
  }

  /** @docs-private */
  blur() {
    this.onTouched();
    this.emitState(true);
  }

  /**
   * @docs-private
   *
   * Implemented as part of DaffFormFieldControl.
   */
  @Input({ transform: booleanAttribute }) disabled = false;

  private _required = false;

  /**
   * @docs-private
   *
   * Implemented as part of DaffFormFieldControl.
   */
  @Input({ transform: booleanAttribute })
  get required(): boolean {
    return this.ngControl?.control?.hasValidator(Validators.required) ?? this._required;
  }
  set required(value: boolean) {
    this._required = value;
  }

  @Input() options: T[] = [];

  /**
   * @docs-private
   */
  get isOpen() {
    return this.openDirective.open;
  }

  /**
   * @docs-private
   *
   * `aria-labelledby` for the select.
   */
  ariaLabelledBy = '';

  /**
   * The unique id of the select options. Defaults to an autogenerated value.
   */
  @Input() optionsId: string = 'daff-select-options' + '-' + ++daffSelectOtionsId;

  constructor(
    private cd: ChangeDetectorRef,
    @Inject(DOCUMENT) private document: Document,
    @Optional() @Self() public ngControl: NgControl,
    private overlay: Overlay,
    private openDirective: DaffOpenableDirective,
    @Optional() private formField: DaffFormFieldComponent,
  ) {
    super(ngControl);

    if(!this.formField) {
      throw new Error('DaffSelectComponent needs to be used with the DaffFormFieldComponent.');
    }

    this.ariaLabelledBy = this.formField.id;

    this.openDirective.stateless = false;

    this.document.addEventListener('keydown', (event) => {
      if (event.key === 'Tab' && this.isOpen) {
        event.preventDefault();
        event.stopPropagation();

        this.focusOptionsList();
      }
    });

    if (this.ngControl != null) {
      this.ngControl.valueAccessor = this;
    }
  }

  /**
   * @docs-private
   */
  @ViewChild('field') buttonElement: ElementRef<HTMLButtonElement>;
  /**
   * @docs-private
   */
  @ViewChild('optionsTemplate') optionsTemplatePortal: TemplatePortal<unknown>;
  /**
   * @docs-private
   */
  @ViewChild('optionsEl', { read: ElementRef<HTMLDivElement> }) optionsElement: ElementRef<HTMLDivElement>;

  /**
   * @docs-private
   */
  @ContentChild(DaffSelectOptionDirective) optionTemplate?: DaffSelectOptionDirective;

  /**
   * @docs-private
   */
  get value() {
    return this._value;
  }

  /**
   * @docs-private
   */
  get highlighted(): number {
    return this._highlighted;
  }

  set highlighted(val: number) {
    this._highlighted = val;
    this.cd.markForCheck();
  }

  private focusOptionsList() {
    this.optionsElement?.nativeElement.focus();
  }

  private focusButton() {
    this.buttonElement?.nativeElement.focus();
  }

  /**
   * @docs-private
   */
  ngOnDestroy(): void {
    this._destroyed.next(true);
    this._overlay?.dispose();
  }

  private onChange(value: T): void {};
  private onTouched(): void {};

  /**
   * @docs-private
   */
  writeValue(value: T): void {
    this._value = value;
    this.cd.markForCheck();
  }

  /**
   * @docs-private
   */
  registerOnChange(fn: (value: T) => void): void {
    this.onChange = fn;
  }

  /**
   * @docs-private
   */
  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  /**
   * @docs-private
   */
  flushValue() {
    this.ngControl?.control?.setValue(this._value);
  }

  /**
   * @docs-private
   */
  ngOnInit() {
    this.stateChanges = merge(
      this._stateChanges.asObservable(),
      this.ngControl ? this.ngControl.statusChanges : of(undefined),
    ).pipe(
      map(() => this.state),
      tap((state) => this.disabled = state.disabled),
    );
  }

  /**
   * Opens the options list.
   */
  open(event?: KeyboardEvent | MouseEvent) {
    event?.preventDefault();
    event?.stopPropagation();

    if (!this.openDirective.open) {
      this.openDirective.open = true;

      if (this._value) {
        this._highlighted = this.options.findIndex((v) => v === this._value);
      }

      const formFieldEl = this.formField.elementRef.nativeElement;
      const formFieldWidth = formFieldEl.getBoundingClientRect().width;

      this._overlay = this.overlay.create({
        hasBackdrop: true,
        backdropClass: 'cdk-overlay-transparent-backdrop',
        scrollStrategy: this.overlay.scrollStrategies.block(),
        disposeOnNavigation: true,
        width: `${formFieldWidth}px`,
        positionStrategy: this.overlay
          .position()
          .flexibleConnectedTo(formFieldEl)
          .withPositions([
            {
              originX: 'start',
              originY: 'bottom',
              overlayX: 'start',
              overlayY: 'top',
              offsetY: 2,
            },
            {
              originX: 'start',
              originY: 'top',
              overlayX: 'start',
              overlayY: 'bottom',
              offsetY: -2,
            },
          ]),
      });

      this._overlay.attachments().pipe(
        takeUntil(this._destroyed),
        delay(0),
      ).subscribe(() => {
        this.focusOptionsList();
      });

      this._overlay.attach(this.optionsTemplatePortal);

      this._overlay.backdropClick().pipe(
        takeUntil(this._destroyed),
      ).subscribe(() => this.close());
      this.cd.markForCheck();
    }
  }

  /**
   * Closes the options list.
   */
  close(event?: KeyboardEvent | MouseEvent) {
    event?.preventDefault();
    event?.stopPropagation();

    if (this.openDirective.open) {
      this.openDirective.open = false;
      this.cd.markForCheck();

      // do we actually have to dispose and recreate the overlay every time we want to close the dropdown?
      this._overlay?.dispose();
      this._overlay = null;
      this.focusButton();
    }
  }

  /**
   * Selects the value in a particular position in the options list.
   */
  private selectValueInPosition(position: number) {
    if (position >= 0 && position < this.options.length) {
      this.writeValue(this.options[position]);
    }

    this.close();
  }

  /**
   * Selects an option.
   */
  selectOption(option: T) {
    this._value = option;
    this.onChange(this._value);

    this.close();
  }

  /**
   * Selects the option referenced by the highlighted index.
   */
  selectHighlighted(event?: KeyboardEvent | MouseEvent) {
    event?.preventDefault();
    event?.stopPropagation();
    this.selectValueInPosition(this._highlighted);

    this.onChange(this._value);
  }

  /**
   * Highlights the next option in the list.
   */
  highlightNext(event?: KeyboardEvent | MouseEvent) {
    event?.preventDefault();
    event?.stopPropagation();
    this._highlighted = this._highlighted < this.options.length - 1 ? this._highlighted + 1 : 0;
    (<HTMLElement>event?.target).children[this._highlighted].scrollIntoView();
  }

  /**
   * Highlights the previous option in the list.
   */
  highlightPrevious(event?: KeyboardEvent | MouseEvent) {
    event?.preventDefault();
    event?.stopPropagation();
    this._highlighted = this._highlighted > 0 ? this._highlighted - 1 : this.options.length - 1;
    (<HTMLElement>event?.target).children[this._highlighted].scrollIntoView();
  }
}
