/**
 * The subset of package.json fields the package table generator reads.
 */
export interface PackageInfo {
  name: string;
  private?: boolean;
}

const TABLE_START = '<!-- AUTOGENERATE_PACKAGE_START -->';
const TABLE_END = '<!-- AUTOGENERATE_PACKAGE_END -->';
const TABLE_REGEX = new RegExp(`${TABLE_START}.*${TABLE_END}`, 's');

const buildRow = (packageName: string): string =>
  `| [@daffodil/${packageName}](/libs/${packageName}/README.md) | [![latest](https://img.shields.io/npm/v/%40daffodil%2F${packageName}/latest.svg)](https://npmjs.com/package/@daffodil/${packageName}) | [![experimental](https://img.shields.io/static/v1.svg?label=stability&message=experimental&color=orange)](https://www.github.com/graycoreio/daffodil)`;

/**
 * Builds the autogenerated package table from the given package.jsons, skipping private packages.
 */
export const buildPackageTable = (packages: PackageInfo[]): string =>
  [
    TABLE_START,
    '| Package | Version | Stability |',
    '|---|---|---|',
    ...packages
      .filter((pkg) => !pkg.private)
      .map((pkg) => buildRow(pkg.name.replace('@daffodil/', ''))),
    TABLE_END,
  ].join('\n');

/**
 * Replaces the autogenerated package table section of the README with the given table.
 */
export const replacePackageTable = (readme: string, table: string): string =>
  readme.replace(TABLE_REGEX, table);
