/**
 * The error codes applicable to the filter behaviors of `@daffodil/product`.
 *
 * @docs-private
 */
export enum DaffProductFilterErrorCodes {
  FILTER_REQUEST_TYPE_MISMATCH = 'DAFF_PRODUCT_FILTER_REQUEST_TYPE_MISMATCH',
  FILTER_REQUEST_NAME_MISMATCH = 'DAFF_PRODUCT_FILTER_REQUEST_NAME_MISMATCH',
  FILTER_NOT_FOUND = 'DAFF_PRODUCT_FILTER_NOT_FOUND',
  UNKNOWN_FILTER_TYPE = 'DAFF_PRODUCT_UNKNOWN_FILTER_TYPE',
}
