<?php
/**
 * Copyright © Graycore. All rights reserved.
 */

/** @var \Graycore\CmsAiBuilder\Block\Adminhtml\Editor $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<script>
<?php $assetsPath = $block->getViewFileUrl('Graycore_CmsAiBuilder::js/editor'); ?>
window.CmsAiBuilderUrl = '<?= $escaper->escapeUrl($block->getUrl('CmsAiBuilder/generate/index')) ?>';
window.CmsAiRendererUrl = '<?= $escaper->escapeUrl($block->getUrl('CmsAiBuilder/renderer/index')) ?>';
window.CmsAiBuilderAssetsPath = '<?= $escaper->escapeUrl($assetsPath) ?>';
window.CmsAiBuilderConfig = {
    polyfillsScript: '<?= $escaper->escapeJs($block->getPolyfillsScriptPath()) ?>',
    mainScript: '<?= $escaper->escapeJs($block->getMainScriptPath()) ?>',
    rendererConfig: <?= /* @noEscape */ $block->getRendererConfigJson() ?>
};

// Configure Monaco environment for web workers
window.MonacoEnvironment = {
  getWorkerUrl: (_moduleId, label) => {
    if (label === 'json') {
      return window.CmsAiBuilderAssetsPath + '/browser/assets/monaco/min/vs/assets/json.worker-DghZTZS7.js';
    }
    return window.CmsAiBuilderAssetsPath + '/browser/assets/monaco/min/vs/assets/editor.worker-DM0G1eFj.js';
  },
};
</script>
