# File: simple-param.yml
parameters:
- name: 'artifactName'
  type: string 
  default: false
- name: 'token'
  type: string 
  default: false
- name: 'nowOrg'
  type: string 
  default: false
- name: 'nowProjectId'
  type: string 
  default: false
- name: 'prod'
  type: boolean
  default: false

steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: '${{ parameters.artifactName }}'

  - script: NOW_ORG_ID=$org NOW_PROJECT_ID=$projectId npx vercel --token=$token
    workingDirectory: '$(System.ArtifactsDirectory)/${{ parameters.artifactName }}'
    displayName: 'Deploy ${{ parameters.artifactName }} to Vercel'
    condition: and(succeeded(), eq('${{ parameters.prod }}', false))
    env:
      token: ${{ parameters.token }}
      org: ${{ parameters.nowOrg }}
      projectId: ${{ parameters.nowProjectId }}

  - script: NOW_ORG_ID=$org NOW_PROJECT_ID=$projectId npx vercel --token=$token --prod
    workingDirectory: '$(System.ArtifactsDirectory)/${{ parameters.artifactName }}'
    displayName: 'Deploy ${{ parameters.artifactName }} to Vercel (Prod)'
    condition: and(succeeded(), eq('${{ parameters.prod }}', true))
    env:
      token: ${{ parameters.token }}
      org: ${{ parameters.nowOrg }}
      projectId: ${{ parameters.nowProjectId }}