import { NgTemplateOutlet } from '@angular/common';
import {
  Component,
  ViewEncapsulation,
  AfterContentInit,
  AfterContentChecked,
  ChangeDetectorRef,
  ChangeDetectionStrategy,
  AfterViewInit,
  isDevMode,
  ElementRef,
  input,
  contentChild,
  signal,
  computed,
} from '@angular/core';

import {
  DaffPrefixDirective,
  DaffSuffixDirective,
  DaffSkeletonableDirective,
  DaffFormLabelDirective,
} from '@daffodil/design';
import {
  DaffErrorMessageComponent,
  DaffHintComponent,
  DaffFormFieldLabelDirective,
} from '@daffodil/design/form';

import { DaffFormFieldActionDirective } from '../action/action.directive';
import { DaffFormFieldControl } from '../form-field-control';

let daffFormFieldId = 0;

export type DaffFormFieldAppearance = 'fluid' | 'fixed';

enum DaffFormFieldAppearanceEnum {
  Fluid = 'fluid',
  Fixed = 'fixed',
}

export const DaffFormFieldMissingControlMessage = 'A DaffFormFieldComponent must contain a DaffFormFieldControl';

/**
 * DaffFormFieldComponent is a wrapping component that provides consistent styling and behavior for form control elements.
 */
@Component({
  selector: 'daff-form-field',
  templateUrl: './form-field.component.html',
  styleUrl: './form-field.component.scss',
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    NgTemplateOutlet,
  ],
  host: {
    class: 'daff-form-field',
    '[class.is-native-select]': 'isNativeSelect()',
    '[class.has-prefix]': '_prefix()',
    '[class.has-suffix]': '_suffix()',
    '[class.has-action]': '_action()',
    '[class.daff-error]': 'isError()',
    '[class.daff-disabled]': 'isDisabled()',
    '[class.daff-valid]': 'isValid()',
    '[class.daff-focused]': 'isFocused',
    '[class.daff-raised]': 'isRaised',
    '[class.fluid]': 'appearance() === "fluid"',
    '[class.fixed]': 'appearance() === "fixed"',
  },
  hostDirectives: [
    {
      directive: DaffSkeletonableDirective,
      inputs: ['skeleton'],
    },
  ],
})
export class DaffFormFieldComponent implements AfterContentInit, AfterContentChecked, AfterViewInit {
  /** @docs-private */
  isNativeSelect = computed(() => this._control()?.controlType === 'native-select');

  constructor(
    private cd: ChangeDetectorRef,
    public elementRef: ElementRef,
  ) {}

  /** @docs-private */
  _prefix = contentChild(DaffPrefixDirective);

  /** @docs-private */
  _suffix = contentChild(DaffSuffixDirective);

  /**
   * @docs-private
   *
   * The child form control that the form field manages.
   */
  _control = contentChild(DaffFormFieldControl);

  /**
   * @docs-private
   *
   * @deprecated Deprecated in version 0.86.0. Will be removed in version 1.0.0.
   */
  _formLabelDirective = contentChild(DaffFormLabelDirective);

  /**
   * @docs-private
   */
  _formFieldLabelDirective = contentChild(DaffFormFieldLabelDirective);

  /**
   * @docs-private
   */
  _action = contentChild(DaffFormFieldActionDirective);

  /**
   * @docs-private
   */
  private _hint = contentChild(DaffHintComponent);

  /**
   * @docs-private
   */
  private _error = contentChild(DaffErrorMessageComponent);

  /**
   * @docs-private
   *
   * Tracking property to keep a record of whether or not the
   * form field should be marked as error.
   */
  isError = signal(false);

  /**
   * @docs-private
   *
   * Tracking property to keep a record of whether or not the
   * form field contains any user input.
   */
  isFilled = signal(false);

  /**
   * @docs-private
   *
   * Tracking property to keep a record of whether or not the
   * form field should be marked as disabled.
   */
  isDisabled = signal(false);

  /**
   * @docs-private
   *
   * Tracking property to keep a record of whether or not the
   * form field should be marked as valid.
   */
  isValid = signal(false);

  /**
   * @docs-private
   *
   * Determines whether or not the form field should display its focused state.
   */
  get isFocused() {
    return this._control()?.focused;
  }

  /**
   * @docs-private
   */
  get isRaised() {
    return this._control()?.raised || this.isFilled();
  }

  /**
   * The appearance of the form field. Defaults to `fluid`.
   */
  appearance = input(DaffFormFieldAppearanceEnum.Fluid, {
    transform: (value: DaffFormFieldAppearance | '' | null | undefined) =>
      value || DaffFormFieldAppearanceEnum.Fluid,
  });

  /**
   * @docs-private
   */
  isFixed = computed(() => this.appearance() === DaffFormFieldAppearanceEnum.Fixed);

  /**
   * The unique id of the form field. Defaults to an autogenerated value. When using this,
   * it's your responsibility to ensure that the id for each form field is unique.
   *
   * It gets assigned to the `for` attribute on the `<label>` inside of the form field.
   */
  id = input('daff-form-field-' + ++daffFormFieldId);

  /**
   * @docs-private
   */
  hasHint = computed(() => !!this._hint());

  /**
   * @docs-private
   */
  hintId = computed(() => this.id() + '-hint');

  /**
   * @docs-private
   */
  hasErrorMessage = computed(() => !!this._error());

  /**
   * @docs-private
   */
  errorMessageId = computed(() => this.id() + '-error');

  /**
   * @docs-private
   */
  autoLabelId = computed(() => this._control()?.supportsAutoLabelling ? this.id() : null);

  /**
   * @docs-private
   */
  customId = computed(() => this._control()?.supportsAutoLabelling ? null : this.id());

  /**
   * @docs-private
   *
   * Displays a console warning if the `DaffFormFieldLabelDirective` is not used on controls (native HTML control elements) that support auto-labelling.
   */
  ngAfterViewInit() {
    if (isDevMode()) {
      if (!this._formFieldLabelDirective() && this._control()?.supportsAutoLabelling && !(this._control()?.id)) {
        console.warn(
          `Accessibility Warning: The form field with id "${this.id()}" uses a control that supports auto-labelling, but no <daff-form-label> component was found.\n\n` +
          `1. Add a <daff-form-label> component (recommended)\n` +
          `2. OR manually set an 'id' on your input and matching 'for' attribute on your <label>.\n\n` +
          `Why this matters: Proper labelling ensures assistive technologies can identify form fields correctly.`,
        );
      }

      if(this._suffix() && this._action() && !this.isFixed()) {
        console.warn(
          `UI consideration for form field with id "${this.id()}":\n\n` + `In a fluid appearance, avoid using suffix alongside an action.`,
        );
      };
    }
  }

  /**
   * Validates whether or not the form field is in a "usable" state.
   */
  private _validateFormControl() {
    if (!this._control()) {
      throw new Error(DaffFormFieldMissingControlMessage);
    }
  }

  /**
   * @docs-private
   *
   * Lifecycle hook to verify that the form field has an acceptable
   * child control instance. Mostly useful for development-time
   * validation of usage.
   */
  ngAfterContentInit() {
    this._validateFormControl();

    this._control()?.stateChanges?.subscribe(({ filled, disabled, error, valid }) => {
      this.isFilled.set(filled);
      this.isError.set(error);
      this.isDisabled.set(disabled);
      this.isValid.set(valid);

      this.cd.markForCheck();
    });
  }

  /**
   * @docs-private
   *
   * Lifecycle hook to verify that the form field has an acceptable
   * child control instance. Mostly useful for development-time
   * validation of usage.
   */
  ngAfterContentChecked() {
    this._validateFormControl();
  }
}
