import {
  Directive,
  Inject,
  TemplateRef,
  OnInit,
  isDevMode,
  input,
  computed,
} from '@angular/core';

import { DaffMediaGalleryRegistration } from '../helpers/media-gallery-registration.interface';
import { DAFF_MEDIA_GALLERY_TOKEN } from '../helpers/media-gallery-token';

let uniqueThumbnailId = 0;

/**
 * DaffThumbnailDirective is a structural directive used to mark elements as thumbnails within the `DaffMediaGalleryComponent`.
 *
 * ```html
 * <ng-template daffThumbnail></ng-template>
 * ```
 */
@Directive({
  selector: '[daffThumbnail]',
})
export class DaffThumbnailDirective implements OnInit {

  private _increment = uniqueThumbnailId;

  /**
   * @docs-private
   *
   * The autogenerated unique id for a thumbnail.
   */
  id = computed(() => this.gallery.id() + '-thumbnail-' + this._increment);

  /**
   * @docs-private
   *
   * The unique id of the selected thumbnail.
   */
  selectedThumbnailId = computed(() => this.id() + '-selected');

  /**
   * The file path to a thumbnail, presumably an image.
   */
  thumbnailSrc = input<string | undefined>(undefined);

  /**
   * Provides an accessible label for a thumbnail.
   */
  label = input<string | undefined>(undefined);

  /** Indicates whether the thumbnail represents a video. */
  isVideo = input(false);

  constructor(
    /**
     * @docs-private
     */
    @Inject(DAFF_MEDIA_GALLERY_TOKEN) public gallery: DaffMediaGalleryRegistration,
    /**
     * @docs-private
     */
    public templateRef: TemplateRef<unknown>,
  ) {
    uniqueThumbnailId++;
  }

  /**
   * @docs-private
   */
  ngOnInit() {
    if(!this.label() && isDevMode()) {
      console.warn('The thumbnail ' + this.id() + ' is missing a label.');
    }
  }
}
