import {
  Directive,
  Inject,
  Input,
  TemplateRef,
  OnInit,
  isDevMode,
} from '@angular/core';

import { DaffMediaGalleryRegistration } from '../helpers/media-gallery-registration.interface';
import { DAFF_MEDIA_GALLERY_TOKEN } from '../helpers/media-gallery-token';

let uniqueThumbnailId = 0;

/**
 * DaffThumbnailDirective is a structural directive used to mark elements as thumbnails within the `DaffMediaGalleryComponent`.
 *
 * ```html
 * <ng-template daffThumbnail></ng-template>
 * ```
 */
@Directive({
  selector: '[daffThumbnail]',
})
export class DaffThumbnailDirective implements OnInit {

  private _increment = uniqueThumbnailId;

  /**
   * @docs-private
   *
   * The autogenerated unique id for a thumbnail.
   */
  get id(): string {
    return this.gallery.id + '-thumbnail-' + this._increment;
  }

  /**
   * @docs-private
   *
   * The unique id of the selected thumbnail.
   */
  get selectedThumbnailId(): string {
    return this.id + '-selected';
  }

  /**
   * The file path to a thumbnail, presumably an image.
   */
  @Input() thumbnailSrc = undefined;

  /**
   * Provides an accessible label for a thumbnail.
   */
  @Input() label: string = undefined;

  /** Indicates whether the thumbnail represents a video. */
  @Input() isVideo = false;

  constructor(
    /**
     * @docs-private
     */
    @Inject(DAFF_MEDIA_GALLERY_TOKEN) public gallery: DaffMediaGalleryRegistration,
    /**
     * @docs-private
     */
    public templateRef: TemplateRef<unknown>,
  ) {
    uniqueThumbnailId++;
  }

  /**
   * @docs-private
   */
  ngOnInit() {
    if(!this.label && isDevMode()) {
      console.warn('The thumbnail ' + this.id + ' is missing a label.');
    }
  }
}
