# specific branch build with batching
trigger:
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - .azure/daffio
pr:
  autoCancel: true
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - .azure/daffio
variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
  node_version: 10.x

stages:
  - stage: Daffodil_CI
    displayName: Daffodil CI
    jobs:
      - job: Lint
        displayName: Lint
        pool:
          vmImage: 'Ubuntu 16.04'
        strategy:
          matrix:
            node_10_x:
              node_version: 10.x
        steps:
          - template: ./templates/setup-node.yml

          - script: npx lerna run lint
            displayName: Lint

      - job: Build_And_Test
        displayName: Build And Test
        pool:
          vmImage: 'Ubuntu 16.04'
        strategy:
          matrix:
            node_10_x:
              node_version: 10.x
        steps:
          - template: ./templates/setup-node.yml

          - script: npx lerna run build && npx lerna run test
            displayName: Build & Test

          - template: ./templates/codeclimate.yml

          - script: npx lerna run reportcoverage
            displayName: Generate Coverage Report

          - script: |
              ./cc-test-reporter sum-coverage coverage/cc.*.json
              ./cc-test-reporter -r $token upload-coverage
            displayName: Report Code Climate
            env:
              token: $(CODECLIMATE_TOKEN_DAFFODIL)

          - task: CopyFiles@2
            displayName: Prepare Artifact Staging Directory
            inputs:
              sourceFolder: dist
              contents: '**/*'
              targetFolder: $(Build.ArtifactStagingDirectory)

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Daff.io Serverless Artifact'
            inputs:
              pathtoPublish: '$(Build.ArtifactStagingDirectory)/apps/daffio'
              artifactName: 'daffio-serverless'
              parallel: true
              parallelCount: 8
  - stage: preview
    displayName: Preview Environment
    jobs:
      - deployment: deploy_daffio_preview
        displayName: Deploy Daff.io
        condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/pull'))
        environment: 'daffio-pr-preview'
        variables:
          - group: daffio-now
          - group: daffio-preview-now
        strategy:
          runOnce:
            deploy: 
              steps:
                - task: Bash@3
                  inputs:
                    targetType: 'inline'
                    script: 'env | sort'
                - template: ../templates/now-deployment.yml
                  parameters:
                    artifactSource: graycoreio-daffodil-build 
                    artifactName: daffio-serverless
                    token: $(NOW_DEPLOYMENT_TOKEN)
                    nowOrg: $(NOW_ORG)
                    nowProjectId: $(DAFFIO_PREVIEW_NOW_PROJECTID)
  - stage: next
    displayName: Daff.io Next Environment
    jobs:
      - deployment: deploy_next
        displayName: Deploy
        condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/develop'))
        environment: 'daffio-next'
        variables:
          - group: daffio-now
          - group: daffio-next-now
        strategy:
          runOnce:
            deploy: 
              steps:
              - template: ../templates/now-deployment.yml
                parameters:
                  artifactSource: graycoreio-daffodil-build 
                  artifactName: daffio-serverless
                  token: $(NOW_DEPLOYMENT_TOKEN)
                  nowOrg: $(NOW_ORG)
                  nowProjectId: $(DAFFIO_NEXT_NOW_PROJECTID)
                  prod: true