# specific branch build with batching
trigger:
  branches:
    include:
      - master
      - develop
pr:
  autoCancel: true
  branches:
    include:
      - master
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

stages:
  - stage: Daffodil_CI
    displayName: Daffodil CI
    variables:
      # These are the files that, when changed, will incur a full build
      buildRootFiles: angular.json | lerna.json | package.json | package-lock.json | tsconfig.json | tools/karma/karma.conf.js
    jobs:
      - job: Lint
        displayName: Lint

        strategy:
          matrix:
            node_16_x:
              node_version: 16.x
        steps:
          - template: ./templates/setup-node.yml

          # This cache step is purely for the purpose of diffing the specified files
          # These files are those that would incur a repository-wide linting change
          # Therefore every package must be relinted
          - task: Cache@2
            displayName: Cache .vscode For Lint Diff
            inputs:
              key: '"lint" | "$(node_version)" | angular.json | lerna.json | package.json | package-lock.json | .prettierrc | .stylelintrc | .eslintrc.js'
              path: $(Build.SourcesDirectory)/.vscode
              cacheHitVar: ngLintCache

          - template: ./templates/lerna-lint.yml
            parameters:
              incremental: |
                and(
                  eq(variables['ngLintCache'], 'true'),
                  eq(variables['Build.Reason'], 'PullRequest')
                )


      - job: Build_And_Test
        displayName: Build
        strategy:
          matrix:
            node_16_x:
              node_version: 16.x
        steps:
          - template: ./templates/setup-node.yml
          - template: ./templates/get-branch-sha.yml
            parameters:
              stepName: GetBuildCacheCommitSHA
              # for PR builds, we want to use the cache from the target commit
              ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
                branch: origin/$(System.PullRequest.TargetBranch)
              # for non PR builds, we want to create the cache for the current commit
              ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
                branch: origin/$(Build.SourceBranchName)

          # This cache step will only hit if the specified files have not changed
          # If a cache miss occurs, we know that a full build must happen
          - task: Cache@2
            displayName: Cache Built Packages
            inputs:
              key: '"dist" | "$(node_version)" | $(buildRootFiles) | "$(GetBuildCacheCommitSHA.BranchSHA)" | "ngv13"'
              path: $(Build.SourcesDirectory)/dist
              cacheHitVar: ngBuildCache

          - template: ./templates/lerna-build-test.yml
            parameters:
              incremental: |
                and(
                  eq(variables['ngBuildCache'], 'true'),
                  eq(variables['Build.Reason'], 'PullRequest')
                )

          - task: CopyFiles@2
            displayName: Prepare Artifact Staging Directory
            inputs:
              sourceFolder: dist
              contents: '**/*'
              targetFolder: $(Build.ArtifactStagingDirectory)

          - task: ArchiveFiles@2
            displayName: Archive dist Folder
            inputs:
              rootFolderOrFile: $(Build.SourcesDirectory)/dist
              includeRootFolder: false
              quiet: true
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-dist.zip

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Dist Artifact'
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-dist.zip
              artifactName: 'dist-artifact'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Daff.io Serverless Artifact'
            inputs:
              pathtoPublish: '$(Build.ArtifactStagingDirectory)/apps/daffio'
              artifactName: 'daffio-serverless'
              parallel: true
              parallelCount: 8

      - job: compute_packages
        displayName: Compute Packages to Test
        dependsOn: []
        steps:
        - bash: |
            npm ci
            PACKAGES_TO_TEST=$(npx lerna ls --since="origin/develop" --all --json | jq 'reduce .[] as $i ({}; .[$i.name] = $i)' -c)
            echo "##vso[task.setvariable variable=packagesToTest;isOutput=true;]$PACKAGES_TO_TEST"
          name: packages
      - job: test
        displayName: "Test"
        condition: and(succeeded(), ne(dependencies.compute_packages.outputs['packages.packagesToTest'], '{}'))
        variables:
          node_version: 16.x
        strategy:
          matrix: $[ dependencies.compute_packages.outputs['packages.packagesToTest'] ]
        dependsOn:
          - compute_packages
          - Build_And_Test
        steps:
        - task: DownloadPipelineArtifact@2
          displayName: Download Dist Artifact
          inputs:
            artifact: dist-artifact
            path: $(Pipeline.Workspace)

        - task: ExtractFiles@1
          displayName: Extract Dist Archive
          inputs:
            archiveFilePatterns: '$(Pipeline.Workspace)/$(Build.BuildId)-dist.zip'
            destinationFolder: $(Build.SourcesDirectory)/dist
            cleanDestinationFolder: true
        - template: ./templates/setup-node.yml
        - template: ./templates/codeclimate.yml
        - template: ./templates/get-branch-sha.yml
          parameters:
            stepName: GetBuildCacheCommitSHA
            # for PR builds, we want to use the cache from the target commit
            ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
              branch: origin/$(System.PullRequest.TargetBranch)
            # for non PR builds, we want to create the cache for the current commit
            ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
              branch: origin/$(Build.SourceBranchName)

        # the publish step will fail and stop CI if the coverage folder doesn't exist
        - script: mkdir -p $(Build.SourcesDirectory)/coverage
          displayName: Ensure Coverage Directory is Present

        - script: npx lerna run test --scope="$(name)"
          displayName: Run tests for $(name)

        - task: PublishPipelineArtifact@1
          inputs:
            # TODO: only publish cc.*.json reports, not entire folder
            targetPath: $(Build.SourcesDirectory)/coverage

  - stage: preview
    displayName: Preview Environment
    jobs:
      - deployment: deploy_daffio_preview
        displayName: Deploy Daff.io
        condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/pull'))
        environment: 'daffio-pr-preview'
        variables:
          - group: daffio-now
          - group: daffio-preview-now
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ./templates/now-deployment.yml
                  parameters:
                    artifactName: daffio-serverless
                    token: $(NOW_DEPLOYMENT_TOKEN)
                    nowOrg: $(NOW_ORG)
                    nowProjectId: $(DAFFIO_PREVIEW_NOW_PROJECTID)
  - stage: next
    displayName: Daff.io Next Environment
    jobs:
      - deployment: deploy_next
        displayName: Deploy
        condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/develop'))
        environment: 'daffio-next'
        variables:
          - group: daffio-now
          - group: daffio-next-now
        strategy:
          runOnce:
            deploy:
              steps:
              - template: ./templates/now-deployment.yml
                parameters:
                  artifactName: daffio-serverless
                  token: $(NOW_DEPLOYMENT_TOKEN)
                  nowOrg: $(NOW_ORG)
                  nowProjectId: $(DAFFIO_NEXT_NOW_PROJECTID)
                  prod: true
