blank_issues_enabled: false
contact_links:
  - name: Need help?
    url: https://github.com/graycoreio/daffodil/discussions
    about: If you need help on how to use Daffodil, please open a discussion where community members can reply.
  - name: Discord Community
    url: https://discord.gg/BdaJVZ53sR
    about: You can also join Daffodil's discord community for help.