name: Feature Request
description: Propose a new feature or something that you'd like to see changed.
title: 'Title'
type: 'Feature'
body:
  - type: markdown
    attributes:
      value:
        Use this template if you want to request a new feature, or a change to an existing feature. If you are reporting a bug or problem, please use the bug template instead. Please add the appropriate package label(s) to indicate which package this feature is related to.
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: Please describe, in as much detail as you can, what you'd like to see in this feature.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe the use case(s) that the proposed feature would enable. Please try to format as "As a [role], I'd like to be able to do [x]."
    validations:
      required: false
  - type: textarea
    id: prior-work
    attributes:
      label: Prior work
      description: If you got this idea from somewhere, please indicate where you got it from.
    validations:
      required: false
  - type: input
    id: daffodil-version
    attributes:
      label: Daffodil version
      description: What Daffodil version are you currently on?
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Do you have anything to add that doesn't fit in the issue template?
    validations:
      required: false