import {
  Component,
  ChangeDetectionStrategy,
  TemplateRef,
  ViewChild,
  Input,
} from '@angular/core';

let tabId = 1;

/**
 * Tab is a single tab in the tablist that is used to group the label of a tab panel and the tab panel together.
 *
 * A `<daff-tab>` should include the DaffTabLabelComponent and DaffTabPanelComponent components in order to properly structure the UI.
 *
 * @example
 * ```html
 * <daff-tab>
 * 	<daff-tab-label>
 * 		<fa-icon [icon]="faInfoCircle" daffPrefix></fa-icon>
 * 		Tab 1
 * 	</daff-tab-label>
 * 	<daff-tab-panel>
 * 		Tab 1 Panel
 * 	</daff-tab-panel>
 * </daff-tab>
 * ```
 */
@Component({
  selector: 'daff-tab',
  template: `
      <ng-template #label>
        <ng-content select="daff-tab-label"></ng-content>
      </ng-template>
      <ng-template #content>
        <ng-content select="daff-tab-panel"></ng-content>
      </ng-template>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DaffTabComponent {
  /**
   * Whether the tab is disabled.
   */
  @Input() disabled = false;

  /**
   * @docs-private
   */
  @ViewChild('content', { read: TemplateRef, static: true }) contentRef: TemplateRef<any>;

  /**
   * @docs-private
   */
  @ViewChild('label', { read: TemplateRef, static: true }) labelRef: TemplateRef<any>;

  /**
   * A unique id for the tab component. Defaults to an autogenerated value. When using this,
   * it's your responsibility to ensure that the id for each tab is unique.
   */
  @Input() id = 'daff-tab-' + tabId;

  /**
   * @docs-private
   */
  panelId = 'daff-tab-panel-' + tabId;

  constructor() {
    tabId++;
  }
}
