import {
  Component,
  Input,
  ChangeDetectionStrategy,
  ContentChildren,
  QueryList,
  ContentChild,
  ViewEncapsulation,
  booleanAttribute,
} from '@angular/core';

import { DaffOrientableDirective } from '@daffodil/design';
import {
  DaffErrorMessageComponent,
  DaffHintComponent,
} from '@daffodil/design/form-field';

import { DaffCheckboxComponent } from '../checkbox/checkbox.component';
import { DAFF_CHECKBOX_SET } from '../helpers/checkbox-set-token';

let uniqueCheckboxSetId = 0;

@Component({
  selector: 'daff-checkbox-set',
  templateUrl: './checkbox-set.component.html',
  styleUrl: './checkbox-set.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'daff-checkbox-set',
    role: 'group',
    '[attr.aria-labelledby]': 'id',
    '[attr.aria-describedby]': 'ariaDescribedBy',
  },
  hostDirectives: [
    {
      directive: DaffOrientableDirective,
      inputs: ['orientation'],
    },
  ],
  providers: [
    {
      provide: DAFF_CHECKBOX_SET,
      useExisting: DaffCheckboxSetComponent,
    },
  ],
})
export class DaffCheckboxSetComponent {

  constructor(
    private orientation: DaffOrientableDirective,
  ) {
    this.orientation.defaultOrientation = 'vertical';
  }

  /**
   * @docs-private
   *
   * The list of checkboxes in the set.
   */
  @ContentChildren(DaffCheckboxComponent) checkboxes: QueryList<DaffCheckboxComponent>;

  /**
   * The unique id of the checkbox set. Defaults to an autogenerated value. When using this,
   * it's your responsibility to ensure that the id for each checkbox set is unique.
   *
   * It gets assigned to the `for` attribute on the `<label>` inside of the checkbox set.
   */
  @Input() id = 'daff-checkbox-set-' + ++uniqueCheckboxSetId;

  private _required = false;

  private _hasRequiredCheckbox() {
    return this.checkboxes?.some(checkbox => checkbox.required) ?? false;
  }

  /**
   * Whether the checkbox set is required.
   *
   * Can be set explicitly via input, or automatically set to true if any checkbox within the set is required.
   */
  @Input({ transform: booleanAttribute })
  get required(): boolean {
    return this._required || this._hasRequiredCheckbox();
  }
  set required(value: boolean) {
    this._required = value;
  }

  /**
   * @docs-private
   */
  @ContentChild(DaffHintComponent) private _hint: DaffHintComponent;

  /**
   * @docs-private
   */
  hasHint() {
    return this._hint ? true : false;
  }

  /**
   * @docs-private
   */
  hintId = this.id + '-hint';

  /**
   * @docs-private
   */
  @ContentChild(DaffErrorMessageComponent) private _error: DaffErrorMessageComponent;

  /**
   * @docs-private
   */
  hasErrorMessage() {
    return this._error ? true : false;
  }

  /**
   * @docs-private
   */
  errorMessageId = this.id + '-error';

  /**
   * @docs-private
   */
  get ariaDescribedBy() {
    if(this.hasErrorMessage()) {
      return this.errorMessageId;
    } else if(this.hasHint()) {
      return this.hintId;
    } else {
      return null;
    }
  }
}
