coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
      category:
        flags: category
        target: 90%
      core:
        target: 85%
        flags: core
flags:
  category:
    paths:
      - coverage/libs/category
  core:
    paths:
      - coverage/libs/core
