export interface CartItemTotalsResponse {
  item_id: number,
  row_total: number,
  row_total_with_discount: number,
  tax_amount: number,
  tax_percent: number,
  base_tax_amount: number,
  discount_amount: number,
  discount_percent: number,
  extension_attributes: any,

  // price: number,
  // base_price: number,
  // qty: number,
  // base_row_total: number,
  // base_discount_amount: number,
  // price_incl_tax: number,
  // base_price_incl_tax: number,
  // row_total_incl_tax: number,
  // base_row_total_incl_tax: number,
  // options: string,
  // weee_tax_applied: string,
  // weee_tax_applied_amount: number,
  // name: string
}
