/**
 * The error codes applicable to the filter behaviors of `@daffodil/core`.
 */
export enum DaffFilterErrorCodes {
  FILTER_REQUEST_TYPE_MISMATCH = 'DAFF_FILTER_REQUEST_TYPE_MISMATCH',
  FILTER_REQUEST_NAME_MISMATCH = 'DAFF_FILTER_REQUEST_NAME_MISMATCH',
  FILTER_NOT_FOUND = 'DAFF_FILTER_NOT_FOUND',
  UNKNOWN_FILTER_TYPE = 'DAFF_FILTER_UNKNOWN_TYPE',
}
