import {
  Component,
  Input,
  OnInit,
  ViewEncapsulation,
  HostBinding,
  ChangeDetectionStrategy,
} from '@angular/core';

import {
  DaffOpenable,
  DaffOpenableDirective,
} from '@daffodil/design';

import { daffAccordionAnimations } from '../animation/accordion-animation';
import { getAnimationState } from '../animation/accordion-animation-state';

let daffAccordionItemId = 0;
let daffAccordionItemContentId = 0;

@Component({
  selector: 'daff-accordion-item',
  templateUrl: './accordion-item.component.html',
  styleUrls: ['./accordion-item.component.scss'],
  hostDirectives: [{
    directive: DaffOpenableDirective,
    inputs: ['open'],
    outputs: ['toggled'],
  }],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  animations: [
    daffAccordionAnimations.openAccordion,
  ],
})
export class DaffAccordionItemComponent implements OnInit, DaffOpenable {
  /**
   * @docs-private
   */
  @HostBinding('class.daff-accordion-item') class = true;

  /**
   * The unique id of an accordion item. Defaults to an autogenerated value.
   */
  @Input() itemId: string = 'daff-accordion-item' + '-' + ++daffAccordionItemId;

  /**
   * The unique id of an accordion item content. Defaults to an autogenerated value.
   */
  @Input() contentId: string = 'daff-accordion-item-content' + '-' + ++daffAccordionItemContentId;

  /**
   * Whether or not the item is initially opened by default.
   */
  @Input() initiallyExpanded = false;

  /**
   * Disables an accordion item and prevents it from being expanded or collapsed.
   */
  @Input() disabled = false;

  /**
   * @docs-private
   */
  _animationState: string;

  constructor(private openDirective: DaffOpenableDirective) {
    this.openDirective.stateless = false;
  }

  /**
   * @docs-private
   */
  ngOnInit() {
    this.openDirective.open = this.initiallyExpanded ? this.initiallyExpanded : this.openDirective.open;
    this._animationState = getAnimationState(this.openDirective.open);
  }

  get open() {
    return this.openDirective.open;
  }

  /**
   * Reveals the contents of the accordion item.
   */
  reveal() {
    this.openDirective.reveal();
  }

  /**
   * Hides the contents of the accordion item.
   */
  hide() {
    this.openDirective.hide();
  }

  /**
   * Toggles the visibility of the contents of the accordion item.
   */
  toggle() {
    this.openDirective.toggle();
    this._animationState = getAnimationState(this.openDirective.open);
  }
}
