/* eslint-disable quote-props */
import {
  Component,
  OnInit,
  ViewEncapsulation,
  ChangeDetectionStrategy,
  input,
} from '@angular/core';

import {
  DaffDisableable,
  DaffDisableableDirective,
  DaffOpenable,
  DaffOpenableDirective,
} from '@daffodil/design';

let daffAccordionItemId = 0;
let daffAccordionItemContentId = 0;

/**
 * Contains the title and collapsible content. Handles expansion and collapse on user interaction. All `<daff-accordion-item>`s should be grouped inside a `<daff-accordion>`.
 *
 * @example
 * ```html
 *  <daff-accordion-item>
 *    <div daffAccordionItemTitle>Title</div>
 *    <div>Accordion content</div>
 *  </daff-accordion-item>
 * ```
 */
@Component({
  selector: 'daff-accordion-item',
  templateUrl: './accordion-item.component.html',
  styleUrls: ['./accordion-item.component.scss'],
  hostDirectives: [
    {
      directive: DaffOpenableDirective,
      outputs: ['toggled'],
    },
    {
      directive: DaffDisableableDirective,
      inputs: ['disabled'],
    },
  ],
  host: {
    'class': 'daff-accordion-item',
  },
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DaffAccordionItemComponent implements OnInit, DaffOpenable, DaffDisableable {
  /**
   * The unique id of an accordion item. Defaults to an autogenerated value.
   */
  itemId = input<string>('daff-accordion-item' + '-' + ++daffAccordionItemId);

  /**
   * The unique id of an accordion item content. Defaults to an autogenerated value.
   */
  contentId = input<string>('daff-accordion-item-content' + '-' + ++daffAccordionItemContentId);

  /**
   * Whether or not an accordion item is initially expanded by default.
   */
  initiallyExpanded = input(false);

  /**
   * @docs-private
   *
   * Internal function to access the disabled property of the DaffDisableableDirective
   */
  get disabled() {
    return this.disabledDirective.disabled();
  }

  constructor(
    private openDirective: DaffOpenableDirective,
    private disabledDirective: DaffDisableableDirective,
  ) {
    this.openDirective.stateless = false;
  }

  /**
   * @docs-private
   */
  ngOnInit() {
    this.openDirective.open.update(() => this.initiallyExpanded() ? this.initiallyExpanded() : this.openDirective.open()) ;
  }

  /**
   * @docs-private
   */
  get open() {
    return this.openDirective.open;
  }

  /**
   * Reveals the contents of the accordion item.
   */
  reveal() {
    this.openDirective.reveal();
  }

  /**
   * Hides the contents of the accordion item.
   */
  hide() {
    this.openDirective.hide();
  }

  /**
   * Toggles the visibility of the contents of the accordion item.
   */
  toggle() {
    this.openDirective.toggle();
  }
}
