/* eslint-disable @angular-eslint/no-input-rename */
import {
  Component,
  ChangeDetectionStrategy,
  Optional,
  signal,
  effect,
  input,
  computed,
} from '@angular/core';

import { DaffRadioSetComponent } from '../radio-set/radio-set.component';

let radioUniqueId = 0;

@Component({
  selector: 'daff-radio',
  templateUrl: './radio.component.html',
  styleUrl: './radio.component.scss',
  host: {
    class: 'daff-radio',
    role: 'radio',
    '[class.focused]': 'focused()',
    '[class.disabled]': 'disabled()',
    '[class.checked]': 'checked()',
    '[attr.aria-checked]': 'checked()',
  },
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DaffRadioComponent {
  /**
   * The value of a radio.
   */
  value = input<any>();

  /**
   * The unique id of a radio. Defaults to an autogenerated value. When using this,
   * it's your responsibility to ensure that the id for each radio is unique.
   */
  id = input<string>(`daff-radio-${radioUniqueId}`);

  /**
   * @docs-private
   * Input property for whether or not this individual radio is disabled.
   */
  _inputDisabled = input<boolean>(false, {
    alias: 'disabled',
  });

  /**
   * Whether or not a radio is disabled. A radio is disabled if either
   * the radio itself is disabled or the parent radio set is disabled.
   */
  disabled = computed(() => this._inputDisabled() || this.radioSet.disabled());

  /**
   * Whether or not a radio is selected.
   */
  checked = computed(() => this.value() === this.radioSet.value());

  // State
  /**
   * @docs-private
   */
  private focused = signal<boolean>(false);

  /**
   * @docs-private
   */
  _tabIndex = signal(0);

  /**
   * @docs-private
   */
  _name = signal<string>(undefined);

  constructor(@Optional() private radioSet: DaffRadioSetComponent) {
    radioUniqueId++;

    effect(() => {
      this._tabIndex.set(this.radioSet.tabIndex());
    });

    effect(() => {
      this._name.set(this.radioSet.name());
    });

    if(!this.radioSet) {
      throw new Error('DaffRadioComponent needs to be used with DaffRadioSetComponent.');
    }
  }

  /**
   * Selects a radio.
   */
  select() {
    this.radioSet.value.set(this.value());
  }

  /**
   * @docs-private
   *
   * Updates focus styling
   */
  onFocus() {
    this.focused.set(true);
  }

  /**
   * @docs-private
   *
   * Updates blur styling
   */
  onBlur() {
    this.focused.set(false);
  }

  /**
   * @docs-private
   */
  onChange(evt: Event) {
    evt.stopPropagation();

    if(!(evt.target instanceof HTMLInputElement)) {
      return;
    }

    if(!(evt.target.checked) || this.disabled()) {
      return;
    }

    this.select();
  };
}
