resources:
  pipelines:
    - pipeline: graycoreio.daffodil.build
      source: graycoreio.daffodil
      trigger: true
trigger: none
pr: none

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
  node_version: 10.x

stages:
  - stage: preview
    displayName: Preview Environment
    jobs:
      - deployment: deploy_daffio_preview
        displayName: Deploy Daff.io
        condition: eq(variables['Build.Reason'], 'ResourceTrigger'), eq(variables['Build.Reason'], 'Manual')
        environment: 'daffio-pr-preview'
        variables:
          - group: daffio-now
          - group: daffio-preview-now
        strategy:
          runOnce:
            deploy: 
              steps:
                - task: Bash@3
                  inputs:
                    targetType: 'inline'
                    script: 'env | sort'
                - template: ../templates/now-deployment.yml
                  parameters:
                    artifactSource: graycoreio.daffodil.build 
                    artifactName: daffio-serverless
                    token: $(NOW_DEPLOYMENT_TOKEN)
                    nowOrg: $(NOW_ORG)
                    nowProjectId: $(DAFFIO_PREVIEW_NOW_PROJECTID)
  - stage: next
    displayName: Daff.io Next Environment
    jobs:
      - deployment: deploy_next
        displayName: Deploy
        condition: eq(variables['build.sourceBranch'], 'refs/heads/develop')
        environment: 'daffio-next'
        variables:
          - group: daffio-now
          - group: daffio-next-now
        strategy:
          runOnce:
            deploy: 
              steps:
              - template: ../templates/now-deployment.yml
                parameters:
                  artifactSource: graycoreio.daffodil.build 
                  artifactName: daffio-serverless
                  token: $(NOW_DEPLOYMENT_TOKEN)
                  nowOrg: $(NOW_ORG)
                  nowProjectId: $(DAFFIO_NEXT_NOW_PROJECTID)
                  prod: true
