resources:
  pipelines:
    - pipeline: graycoreio.daffodil.build
      source: graycoreio.daffodil

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
  node_version: 10.x

stages:
  - stage: preview
    displayName: Preview Environment
    jobs:
      - job: deploy_daffio_preview
        displayName: Deploy Daff.io
        condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
        variables:
          - group: daffio-now
          - group: daffio-preview-now
        steps:
          - template: ../templates/setup-node.yml
          - template: ../templates/now-deployment.yml
            parameters:
              artifactName: daffio-serverless
              token: $(NOW_DEPLOYMENT_TOKEN)
              nowOrg: $(NOW_ORG)
              nowProjectId: $(DAFFIO_PREVIEW_NOW_PROJECTID)
  - stage: next
    displayName: Daff.io Next Environment
    jobs:
      - job: deploy_next
        displayName: Deploy
        condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/develop'))
        variables:
          - group: daffio-now
          - group: daffio-next-now
        steps:
          - template: ../templates/setup-node.yml
          - template: ../templates/now-deployment.yml
            parameters:
              artifactName: daffio-serverless
              token: $(NOW_DEPLOYMENT_TOKEN)
              nowOrg: $(NOW_ORG)
              nowProjectId: $(DAFFIO_NEXT_NOW_PROJECTID)
              prod: true
