name: Daffodil Build PR

on:
  pull_request_target:
    branches:
      - develop

permissions: 
  actions: read
  attestations: read
  checks: read
  contents: read
  deployments: read
  id-token: none
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  security-events: read
  statuses: read

jobs:
  build:
    name: ${{ github.event.pull_request.head.repo.full_name == github.repository && 'Build PR' || 'Build PR Fork' }}
    uses: graycoreio/daffodil/.github/workflows/build.yml@develop
    with: 
      cache-mode: 'read-only'
      ref: ${{ github.event.pull_request.merge_commit_sha }}
    secrets:
      NX_KEY: ${{ secrets.NX_KEY }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ github.event.pull_request.head.repo.full_name == github.repository && secrets.AZURE_NX_CACHE_READWRITE_CONNECTION_STRING || secrets.AZURE_NX_CACHE_READONLY_CONNECTION_STRING }}

  
