name: Daffodil Lint

env:
  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_NX_CACHE_CONNECTION_STRING }}
  NX_KEY: ${{ secrets.NX_KEY }}

on:
  push:
    paths:
      - '**.ts'
      - '**.scss'
      - '**.html'
      - '**.js'
      - '**.json'
      - '.github/**'
    branches:
      - develop
    tags: ["v*"]
  pull_request:
    paths:
      - '**.ts'
      - '**.scss'
      - '**.html'
      - '**.js'
      - '**.json'
      - '.github/**'
    branches:
      - develop

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
        name: Derive appropriate SHAs for base and head for `nx affected` commands
        with:
          main-branch-name: 'develop'

      - uses: graycoreio/github-actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
          use-stamp-cache: true

      - run: npx nx affected --target=lint
