name: Publish Release

on:
  workflow_run:
    workflows:
      - Daffodil Build Release
    types:
      - completed
  workflow_dispatch:

env:
  NX_KEY: ${{ secrets.NX_KEY }}
  NG_BUILD_ENV: production
  NPM_VERSION: 11

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    if: |
      (github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags/v'))

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.ref }}
          fetch-depth: 1

      - uses: graycoreio/github-actions/setup-node@main
        with:
          node-version: 22.21.x
          npm-version: ${{ env.NPM_VERSION }}
          use-stamp-cache: true
          registry-url: 'https://registry.npmjs.org'

      - uses: graycoreio/daffodil/.github/actions/setup-nx-remote-cache@develop
        with:
          cache-mode: read-only
          read-only-azure-connection-string: ${{ secrets.AZURE_NX_CACHE_READONLY_CONNECTION_STRING }}
          read-write-azure-connection-string: ${{ secrets.AZURE_NX_CACHE_READWRITE_CONNECTION_STRING }}
          event-name: ${{ github.event_name }}

      - run: npx nx run-many -t build

      - uses: graycoreio/github-actions/set-versions-from-root@main

      - run: npx nx run-many -t publish
        if: github.event.workflow_run.conclusion == 'success'