import { DAFF_CUSTOMER_PAYMENT_DEFAULT_PAYMENT_DELETION_ERROR_CODE } from './default-payment-deletion';
import { DAFF_CUSTOMER_PAYMENT_INVALID_API_RESPONSE_ERROR_CODE } from './invalid-api-response';
import { DAFF_CUSTOMER_PAYMENT_NOT_FOUND_ERROR_CODE } from './payment-not-found';

export const DaffCustomerPaymentDriverErrorCodes = {
  PAYMENT_NOT_FOUND: DAFF_CUSTOMER_PAYMENT_NOT_FOUND_ERROR_CODE,
  DEFAULT_PAYMENT_DELETION: DAFF_CUSTOMER_PAYMENT_DEFAULT_PAYMENT_DELETION_ERROR_CODE,
  INVALID_API_RESPONSE: DAFF_CUSTOMER_PAYMENT_INVALID_API_RESPONSE_ERROR_CODE,
};
